
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/shilululiu/coding-farmer-config-center
          #配置仓库路径
          search-paths: test
          #访问git仓库的用户名
          username: 17629581571@163.com
          #访问git仓库的密码
          password: 2056096324sll
          #配置中心通过git从远程git库，有时本地的拷贝被污染，
          #这时配置中心无法从远程库更新本地配置,设置force-pull=true，则强制从远程库中更新本地库
          force-pull: true
          #默认从git仓库克隆下载的在C:/Users/<当前用户>/AppData/Local/Temp
          #basedir: D:/ex

server:
  port: 8203


eureka:
  client:
    region: region1
    availability-zones:
      region1: region1-zone1,region1-zone2,region1-zone3
    service-url:
      region1-zone1: http://root:admin@eureka1:8001/eureka/
      region1-zone2: http://root:admin@eureka2:8002/eureka/
      region1-zone3: http://root:admin@eureka3:8003/eureka/
    prefer-same-zone-eureka: true
  instance:
    prefer-ip-address: true
    metadata-map.zone: region1-zone1