
spring:
  application:
    name: springclouddemo
  cloud:
    config:
      #uri则表示配置中心的地址
      # discovery:
      #  enabled: true #启用服务发现
      #   service-id: springcloud-config-server #指定要从eureka获取的config server的服务ID（即：configserverr的applicationName）
      #注：config 客户端在没有 spring.cloud.config.name属性的时候，服务端{application} 获取的是客户端
      #spring.application.name的值，否则，获取的是 spring.cloud.config.name的值。
      #1）、当没有spring.cloud.config.name时，客户端获取的是spring.application.name 所对应的git库中的文件，并且只能获取一个文件
      #2）、当一个项目中有需求要获取多个文件时，就需要用到spring.cloud.config.name这个属性，以逗号分割
      name: application
      profile: test
      #label对应了label部分
      label: master
      bus:
        trace:
          enabled: true # 开启mq的日志追踪
server:
  port: 2345
  rabbitmq:
    host: localhost  # mq的ip地址
    port: 15672 # mq的端口
    password: guest # mq的用户密码
    username: guest # mq的用户名


logging:
  level:
    org.springframework.cloud: debug

  zipkin:
    base-url: http://127.0.0.1:9411/  # zipkin服务器的地址
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      type: rabbit  #使用 rabbitmq 来向 zipkin 发送数据
    sleuth:
      sampler:
        probability: 1  # 设置抽样采集率为100%，默认为0.1，即10%







