spring:
  application:
    name: register-center
  security:
    basic:
      enabled: true # 开启basic认证
    user:
      name: root # 用户名
      password: admin # 密码
eureka:
  instance:
    prefer-ip-address: false #使用ip地址来注册到服务中心，显示的是实例名称
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #设置 注册服务中心，显示的实例名称
    lease-expiration-duration-in-seconds: 30  # 服务失效时间，失效的服务将被剔除。单位：秒，默认：90
    lease-renewal-interval-in-seconds: 5 # 服务续约（心跳）频率，单位：秒，缺省30
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: true  # false表示自己不需要向注册中心注册自己   集群为true
    fetch-registry: true  # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务    集群为true
    region: region1
    availability-zones:
      region1: region1-zone3,region1-zone1,region1-zone2   #取第一个做为此服务分区名
    service-url:
      region1-zone1: http://root:admin@eureka1:8001/eureka/
      region1-zone2: http://root:admin@eureka2:8002/eureka/
      region1-zone3: http://root:admin@eureka3:8003/eureka/
      #  defaultZone: http://rc1:8761/eureka/, http://rc2:8762/eureka/


logging.level.com.netflix:
  eureka: OFF
  discovery: OFF
  profiles: eureka3

server:
  port: 8003

eureka.instance.hostname: eureka3 #Eureka实例所在的主机名
